language: node_js #设置语言

node_js: "10.16.3" #设置语言版本

cache:
  directories:
    - node_modules #缓存依赖

before_install:
  - ls -a
  - pwd

install:
  - npm install -g hexo-cli
  - npm install

before_script:
  - export HEXO_ALGOLIA_INDEXING_KEY=${algolia}

script:
  - hexo clean
  - hexo g
  - hexo algolia

# 设置git提交名，邮箱；替换真实token到_config.yml文件，最后depoy部署
after_script:
  - git config user.name "jianqiao0313"
  - git config user.email "jianqiao0313@gmail.com"
  # 替换同目录下的_config.yml文件中gh_token字符串为travis后台刚才配置的变量，注意此处sed命令用了双引号。单引号无效！
  - sed -i "s/gh_token/${github_token}/g" ./_config.yml
  - hexo deploy
  - mkdir uploadToOss
  - cd uploadToOss
  - git clone https://github.com/jianqiao0313/jianqiao0313.github.io.git
  - git clone https://${github_token}@github.com/jianqiao0313/oss.git
  - ls -a
  - cd oss
  - ls -a
  - pwd
  - npm i
  - node index.js publicPath=../jianqiao0313.github.io preDirPath=uploadToOss region=${region} accessKeyId=${accessKeyId} accessKeySecret=${accessKeySecret} bucket=${bucket}

  

# 只有指定的分支提交时才会运行脚本
branches:
  only:
    - hexo